sudo: required
services:
    - docker

before_install:
    - docker build -t rajnaidu/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true rajnaidu/react-test npm test -- --coverage

after_success:
    - docker build -t rajnaidu/multi-client ./client
    - docker build -t rajnaidu/multi-nginx ./nginx
    - docker build -t rajnaidu/multi-server ./server
    - docker build -t rajnaidu/multi-worker ./worker

    # Log in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

    # Take those images and push them to docker hub
    - docker push rajnaidu/multi-client
    - docker push rajnaidu/multi-nginx
    - docker push rajnaidu/multi-server
    - docker push rajnaidu/multi-worker

    # Deploy to AWS Beanstalk
    deploy:
        edge: true
        provider: elasticbeanstalk
        region: us-east-2
        app: multi-docker
        env: MultiDocker-env
        bucket_name: elasticbeanstalk-us-east-2-766026079825
        bucket_path: docker_multi
        on:
            branch: master
        access_key_id: $AWS_ACCESS_KEY
        secret_access_key:
            secure: $AWS_SECRET_KEY


    - echo "process completed..."